"""Stable semantic projection domain API."""

from .character import (
    VIEWER_ROLES,
    PRIVATE_VIEWERS,
    GROUP_LABELS,
    ROLE_ICONS,
    RESOURCE_CAPABILITIES,
    STATE_LABELS,
    _mapping,
    _sequence,
    actor_definition,
    resolved_catalog,
    _text,
    semantic_field_index,
    field_for_role,
    _preset_snapshot,
    _preset_index,
    _entity_label_index,
    _looks_internal_ref,
    _friendly_mapping_text,
    _display_scalar,
    field_display_value,
    project_actor_view,
)

from .world import (
    actor_values_for_roles,
    _module_definition,
    _definition_items,
    _runtime_collection,
    _state_definition,
    resolve_state_label,
    _definition_index,
    project_quest_view,
    project_faction_view,
    project_npc_view,
    project_world_state_view,
    world_capability_view,
    world_has_capability,
    _owner_key,
    project_resource_view,
    project_story_view,
)

from .session import (
    TECHNICAL_VIEWERS,
    MODULE_PANEL_LABELS,
    NARRATIVE_MODE_LABELS,
    NARRATIVE_PHASE_LABELS,
    DELIVERY_STATE_SPECS,
    FATE_STATE_LABELS,
    TERMINATION_LABELS,
    _as_int,
    _is_technical_viewer,
    world_module_manifest,
    world_module_summary,
    world_module_declared,
    world_protocol_display,
    project_world_summary_view,
    project_module_panel_view,
    project_module_panels,
    project_narrative_control_view,
)

from .delivery import (
    project_delivery_status_view,
    project_delivery_status_items,
    project_actor_fate_view,
    project_actor_fate_summary,
    project_terminal_view,
    project_terminal_report_view,
)
