"""Lifecycle domain API."""

from .world_time import (
    CARD_UNCREATED,
    CARD_DRAFT,
    CARD_PENDING,
    CARD_APPROVED,
    CARD_REJECTED,
    CARD_STATUSES,
    CARD_STAGE_A,
    CARD_STAGE_B,
    CARD_STAGE_C,
    CARD_STAGES,
    CARD_STAGE_STATES,
    STAGED_FIELDS_KEY,
    PARTICIPANT_RESERVED,
    PARTICIPANT_ACTIVE,
    PARTICIPANT_STANDBY,
    PARTICIPANT_AWAY,
    PARTICIPANT_RETIRED,
    PARTICIPANT_ARCHIVED,
    PARTICIPANT_STATUSES,
    SEAT_HOLDING_STATUSES,
    CHOICE_KEYS,
    _RISK_ALIASES,
    _RISK_LABELS,
    SUPPORTED_CARD_FIELD_TYPES,
    DEFAULT_TIME_RULES,
    DEFAULT_CARD_FIELDS,
    DEFAULT_CARD_STATS,
    DEFAULT_OPENING_CHOICES,
    DEFAULT_PROGRESS,
    DEFAULT_CONTENT_BOUNDARIES,
    DEFAULT_NPC_POLICY,
    DEFAULT_CONTEXT_BUDGET,
    DEFAULT_DICE_RULES,
    utc_now,
    deadline_after,
    _bounded_int,
    _optional_seconds,
    normalize_time_rules,
    world_time_rules,
    normalize_progress,
    world_session_modules,
    initial_character_runtime_state,
    player_limits,
    _json_copy,
    _ACTOR_TEXT_FIELDS,
    _localized_actor_source,
)

from .character_creation import (
    _normalize_actor_candidate_contracts,
    _row_value,
    _raw_staged_creation,
    staged_creation,
    field_stage,
    stage_field_projection,
    stage_label,
    _field_filled,
    stage_required_missing,
    stage_lock_field,
    card_stage_state,
    resolve_card_stage,
    card_template,
    card_stat_allocation,
    PROFESSION_PRESET_STAT_MODE,
)

from .validation import (
    uses_profession_preset_stats,
    semantic_field_key,
    find_profession_preset,
    attribute_maps,
    resolve_profession_stats,
    next_fillable_card_step,
    repair_profession_preset_draft,
    validate_card_template_config,
)

from .risk_resolution import (
    MAX_TEAM_CHOICES,
    _normalize_risk_id,
    normalize_choices,
    normalize_model_choices,
    opening_choices,
    fallback_choices,
    parse_choice_input,
    _DURATION_PATTERN,
    parse_duration,
)

from .state_transitions import (
    safe_exit_narrative,
    _CHOICE_LETTER_EMOJI,
    _TEAM_NUMBER_LABELS,
    _RISK_DOT,
    _risk_dot,
    format_choices,
    vote_result,
)
