"""Shared player-facing copy for card candidates (C6 M1/M2).

This module is the single place that converts world preset candidates into
safe, budgeted player text.  Both rendering chains consume the DTOs built
here:

- the interactive prompt chain (``tavern/presentation.py``), and
- the proactive delivery chain (``tavern/card_delivery.py``).

Neither chain interprets raw world mappings any more, so internal contract
fields (``id``/``text_id``/``rule_refs``/``source_refs``/``contract``/...)
can never leak into player-visible copy.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from ..candidates import (
    CANDIDATE_RULE_KEYS,
    normalize_candidate_rules,
)


class CandidateCopyError(ValueError):
    """World content error: a candidate cannot produce valid player copy."""


# ---------------------------------------------------------------------------
# Length budgets (Chinese characters, documented in 02_CHARACTER_CREATION...)
# ---------------------------------------------------------------------------

LABEL_BUDGET = 30
SUMMARY_BUDGET = 90
DETAIL_BUDGET = 70

MAX_ADVANTAGES = 2
MAX_LIMITATIONS = 2
MAX_STORY_HOOKS = 2


# Technical placeholder labels that must never be shown to players as-is.
TECHNICAL_LABELS = frozenset(
    {
        "可用优势",
        "实际边界",
        "适用优势",
        "使用边界",
        "核心强项",
        "资源与场景限制",
    }
)


# Phrases that mark authoring notes / internal technical remarks.  Any text
# containing one of these markers is treated as non-player copy and dropped.
HIDDEN_COPY_MARKERS = (
    "用于定义角色的",
    "为对应场景提供合理的身份",
    "为对应场景提供合理入口",
    "仅覆盖声明范围",
    "不自动授予未注册",
    "主持裁定决定的边界",
    "由主持裁定决定边界",
    "稳定 ID",
    "稳定ID",
    "twp-actor-candidate",
    "text_id",
    "source_refs",
    "preset_sets.",
    "eligibility",
    "conflicts",
    "recommendations",
    "unlocks",
    "resource_modifiers",
    "ability_pool_add",
    "ability_pool_remove",
    "runtime_effect_refs",
    "grant_ref",
)


# Boilerplate generated by an earlier world-authoring pass.  These sentences
# repeat the selected name without explaining what distinguishes the choice.
# They are rejected in the shared copy layer so third-party/older packages also
# fall through to their concrete description or advantage.
GENERIC_SUMMARY_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^在〈[^〉]+〉成长，保留当地记忆、人脉与未解决的问题。?$"),
    re.compile(r"^以〈[^〉]+〉的地位进入所属组织的权限与义务结构。?$"),
    re.compile(r"^来自〈[^〉]+〉的生活经验、习俗与群体关系。?$"),
    re.compile(r"^以〈[^〉]+〉的身份进入社会关系、责任与声誉网络。?$"),
    re.compile(r"^把“[^”]+”作为角色的长期个人目标。?$"),
    re.compile(r"^在〈[^〉]+〉方面具备分层、可核验的受训知识。?$"),
    re.compile(r"^主动承担“[^”]+”带来的承诺、禁忌与关系后果。?$"),
    re.compile(r"^以〈[^〉]+〉作为连接身份、关系或个人线的标志物品。?$"),
    re.compile(r"^与一名〈[^〉]+〉保持可联系的既有关系。?$"),
    re.compile(r"^仍需处理“[^”]+”这项未结义务。?$"),
    re.compile(r"^角色隐瞒着“[^”]+”这一私人事实。?$"),
    re.compile(r"^能够使用〈[^〉]+〉处理相应的日常交流与文本。?$"),
    re.compile(r"^〈[^〉]+〉会成为角色个人线中的持续压力。?$"),
    re.compile(r"^以〈[^〉]+〉作为开场时的常用工具与补给组合。?$"),
    re.compile(r"^带有〈[^〉]+〉这一可见或可感知的血脉特征。?$"),
    re.compile(r"^在休整时承担〈[^〉]+〉这项队伍职责。?$"),
    re.compile(r"^与〈[^〉]+〉建立开场时的合作、敌对或观察关系。?$"),
    re.compile(r"^个人目标；创建个人任务入口。?$"),
)

GENERIC_STORY_HOOK_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^让〈[^〉]+〉在一次关系、调查或资源选择中产生影响。?$"),
    re.compile(r"^让〈[^〉]+〉提出一次帮助、交换或私人请求。?$"),
    re.compile(r"^让〈[^〉]+〉帮助提出一个关键问题，而不是直接跳过调查。?$"),
    re.compile(r"^让〈[^〉]+〉留下警告、证据或可反制的行动。?$"),
    re.compile(r"^让〈[^〉]+〉的社会处境在一次身份或关系选择中产生影响。?$"),
    re.compile(r"^让〈[^〉]+〉的旧人、旧路或旧问题进入当前冒险。?$"),
)


def copy_is_generic(text: Any) -> bool:
    value = str(text or "").strip()
    return any(
        pattern.fullmatch(value)
        for pattern in (*GENERIC_SUMMARY_PATTERNS, *GENERIC_STORY_HOOK_PATTERNS)
    )


# Field key -> entity family used by ``decorate_entity`` for consistent
# player-facing marks (「角色」「地点」「道具」「能力」...).
FIELD_ENTITY_TYPES: Mapping[str, str] = {
    "name": "character",
    "nickname": "character",
    "origin_region": "location",
    "hometown": "location",
    "starting_weapon": "item",
    "starting_armor": "item",
    "loadout": "item",
    "signature_item": "item",
    "abilities": "ability",
    "specialties": "ability",
    "specialization": "ability",
    "weakness": "status",
    "faction_affiliation": "faction",
    "personal_goal": "quest",
    "contact": "character",
    "rival": "character",
}


@dataclass(frozen=True, slots=True)
class CandidatePlayerCopy:
    """Sanitized, budgeted player-facing copy for one preset candidate.

    ``candidate_id`` exists only for internal parsing and generation
    fingerprints; it is never rendered.  Every text field is already cleaned
    and contains no internal contract tokens.
    """

    candidate_id: str
    value: str
    label: str
    summary: str
    advantages: tuple[str, ...]
    limitations: tuple[str, ...]
    story_hooks: tuple[str, ...]
    entity_type: str


def entity_type_for_field(field: Mapping[str, Any] | None) -> str:
    if not isinstance(field, Mapping):
        return ""
    key = str(field.get("key") or "").strip().casefold()
    return FIELD_ENTITY_TYPES.get(key, "")


def player_copy_text(value: Any) -> str:
    """Safe text extraction: containers are never stringified."""

    if isinstance(value, Mapping):
        return ""
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        return ""
    text = (
        str(value or "")
        .replace("NPC", "非玩家角色")
        .replace("DM", "主持人")
        .strip()
    )
    if not text:
        return ""
    if copy_is_generic(text):
        return ""
    if any(marker in text for marker in HIDDEN_COPY_MARKERS):
        return ""
    return text


def _copy_comparable(value: str) -> str:
    return re.sub(
        r"[\s，。；：、「」『』〈〉《》〖〗（）()【】\-–—|]+",
        "",
        str(value or ""),
    )


def copy_is_redundant(detail: str, description: str) -> bool:
    left = _copy_comparable(detail)
    right = _copy_comparable(description)
    if len(left) < 6 or len(right) < 6:
        return False
    return left in right or right in left


_SENTENCE_END = "。；！？!?\n"
_CLAUSE_END = "，、：;"


def truncate_text(text: Any, limit: int) -> str:
    """Truncate to ``limit`` chars without cutting mid-sentence or mid-mark."""

    value = str(text or "").strip()
    if not value or len(value) <= limit:
        return value
    window = value[: limit + 1]
    cut = max(window.rfind(ch) for ch in _SENTENCE_END)
    if cut < limit // 3:
        cut = max(window.rfind(ch) for ch in _CLAUSE_END)
        if cut < limit // 3:
            cut = limit
    else:
        cut += 1
    prefix = value[:cut]
    for open_mark, close_mark in (
        ("「", "」"),
        ("『", "』"),
        ("〈", "〉"),
        ("《", "》"),
        ("〖", "〗"),
        ("（", "）"),
        ("(", ")"),
    ):
        if prefix.count(open_mark) > prefix.count(close_mark):
            close_at = value.find(close_mark, cut)
            if 0 <= close_at <= limit + 12:
                return value[: close_at + 1]
            open_at = prefix.rfind(open_mark)
            if open_at > 0:
                return value[:open_at]
    return prefix


def _mapping_items(
    raw: Any,
    *,
    summary: str,
    budget: int,
    limit: int,
) -> list[str]:
    """Extract one detail category (优势/限制/故事入口) as plain strings.

    Item labels in the two built-in worlds are generic category buckets
    (“可用优势”“实际边界”“常见优势”...) that duplicate the category line, so
    they are never rendered; only the cleaned description is kept and the
    renderer adds the category prefix.
    """

    if isinstance(raw, str):
        items: Sequence[Any] = [raw]
    elif isinstance(raw, Sequence) and not isinstance(raw, (str, bytes)):
        items = raw
    else:
        return []
    out: list[str] = []
    for item in items:
        if isinstance(item, Mapping):
            label = player_copy_text(item.get("label"))
            detail = player_copy_text(item.get("description") or item.get("label"))
            if not detail:
                continue
            if label and detail == label:
                # Bucket-name-only entry carries no real player content.
                continue
        else:
            detail = player_copy_text(item)
            if not detail:
                continue
        if copy_is_redundant(detail, summary):
            continue
        rendered = truncate_text(detail, budget)
        if rendered and rendered not in out:
            out.append(rendered)
        if len(out) >= limit:
            break
    return out


def _summary_for(
    *,
    label: str,
    option_description: str,
    source: Mapping[str, Any],
) -> str:
    """Resolve the summary via ``summary -> description -> role`` chain."""

    candidates = [
        source.get("summary"),
        option_description,
        source.get("description"),
        source.get("role"),
    ]
    for raw in candidates:
        text = player_copy_text(raw)
        if not text:
            continue
        # Compiled candidate descriptions often append a separate limitation
        # clause.  The renderer already gives limitations their own line, so
        # keep the summary focused on the distinguishing trait.
        text = re.split(r"(?:义务/)?限制[：:]", text, maxsplit=1)[0].strip()
        if not text:
            continue
        if _copy_comparable(text) == _copy_comparable(label):
            # Identical to the name: not a summary, try the next source.
            continue
        return truncate_text(text, SUMMARY_BUDGET)
    return ""


def _has_content_fields(source: Mapping[str, Any]) -> bool:
    return any(
        source.get(key) not in (None, "")
        for key in (
            "summary",
            "description",
            "role",
            "advantages",
            "narrative_benefits",
            "limitations",
            "costs_and_limits",
            "story_hooks",
        )
    )


def candidate_player_copy(
    option: Any,
    *,
    field: Mapping[str, Any] | None = None,
    locale: str = "zh-CN",
) -> CandidatePlayerCopy:
    """Build the sanitized player copy for one preset candidate.

    ``option`` is either a normalized preset entry produced by
    :func:`tavern.card_wizard.preset_options` (``{"id", "value", "label",
    "description", "aliases", "source"}``) or a raw world candidate mapping.
    Scalar options (plain name lists) are accepted and yield empty
    ``summary``/details; content-bearing mappings that cannot produce a
    summary raise :class:`CandidateCopyError` instead of silently degrading
    to a bare name.
    """

    source: Mapping[str, Any]
    if isinstance(option, Mapping):
        if isinstance(option.get("source"), Mapping):
            source = option["source"]
            candidate_id = str(option.get("id") or source.get("id") or "").strip()
            value = str(
                option.get("value")
                or source.get("selection_value")
                or source.get("value")
                or source.get("name")
                or option.get("label")
                or ""
            ).strip()
            label = player_copy_text(
                option.get("label")
                or source.get("label")
                or source.get("name")
                or value
            )
            option_description = player_copy_text(option.get("description"))
        else:
            source = option
            candidate_id = str(option.get("id") or option.get("key") or "").strip()
            value = str(
                option.get("value")
                or option.get("selection_value")
                or option.get("name")
                or option.get("label")
                or ""
            ).strip()
            label = player_copy_text(
                option.get("label") or option.get("name") or value
            )
            option_description = player_copy_text(option.get("description"))
    else:
        source = {}
        candidate_id = ""
        value = str(option or "").strip()
        label = player_copy_text(value)
        option_description = ""
    if not label:
        raise CandidateCopyError("候选缺少可显示的名称。")
    label = truncate_text(label, LABEL_BUDGET)
    summary = _summary_for(
        label=label,
        option_description=option_description,
        source=source,
    )
    if not summary and _has_content_fields(source):
        field_label = str(field.get("label") or field.get("key") or "") if isinstance(
            field, Mapping
        ) else ""
        raise CandidateCopyError(
            f"「{field_label}」的候选「{label}」缺少可显示的摘要内容，"
            "请联系管理员检查世界包。"
        )
    advantages = tuple(
        _mapping_items(
            source.get("advantages") or source.get("narrative_benefits") or [],
            summary=summary,
            budget=DETAIL_BUDGET,
            limit=MAX_ADVANTAGES,
        )
    )
    limitations = tuple(
        _mapping_items(
            source.get("limitations") or source.get("costs_and_limits") or [],
            summary=summary,
            budget=DETAIL_BUDGET,
            limit=MAX_LIMITATIONS,
        )
    )
    story_hooks = tuple(
        _mapping_items(
            source.get("story_hooks") or [],
            summary=summary,
            budget=DETAIL_BUDGET,
            limit=MAX_STORY_HOOKS,
        )
    )
    return CandidatePlayerCopy(
        candidate_id=candidate_id,
        value=value,
        label=label,
        summary=summary,
        advantages=advantages,
        limitations=limitations,
        story_hooks=story_hooks,
        entity_type=entity_type_for_field(field),
    )


def candidate_player_copies(
    options: Sequence[Any],
    *,
    field: Mapping[str, Any] | None = None,
    locale: str = "zh-CN",
) -> list[CandidatePlayerCopy]:
    return [
        candidate_player_copy(option, field=field, locale=locale)
        for option in options
    ]


def _rule_source(option: Any) -> Mapping[str, Any]:
    """Merge top-level D1 rule keys over an embedded ``source`` mapping."""

    if not isinstance(option, Mapping):
        return {}
    source = option.get("source")
    merged = dict(source) if isinstance(source, Mapping) else {}
    merged.update(
        {key: option[key] for key in CANDIDATE_RULE_KEYS if key in option}
    )
    return merged


def is_public_candidate(option: Any) -> bool:
    """True when the candidate is not flagged private (safe for group copy)."""

    rules = normalize_candidate_rules(_rule_source(option))
    return str(rules.get("visibility") or "public") == "public"


def player_safe_projection(
    option: Any,
    *,
    field: Mapping[str, Any] | None = None,
    locale: str = "zh-CN",
    recommended: bool = False,
) -> dict[str, Any]:
    """Player-facing projection that can never carry D1 rule internals.

    Only description/advantages/limitations/story hooks survive; eligibility,
    conflicts, unlocks, grants, resource modifiers and effect refs are
    consumed for behaviour and never rendered.
    """

    dto = candidate_player_copy(option, field=field, locale=locale)
    projection: dict[str, Any] = {
        "value": dto.value,
        "label": dto.label,
        "summary": dto.summary,
        "advantages": list(dto.advantages),
        "limitations": list(dto.limitations),
        "story_hooks": list(dto.story_hooks),
        "entity_type": dto.entity_type,
    }
    if recommended:
        projection["recommended"] = True
    return projection


__all__ = [
    "CANDIDATE_RULE_KEYS",
    "CandidateCopyError",
    "CandidatePlayerCopy",
    "DETAIL_BUDGET",
    "FIELD_ENTITY_TYPES",
    "GENERIC_STORY_HOOK_PATTERNS",
    "GENERIC_SUMMARY_PATTERNS",
    "HIDDEN_COPY_MARKERS",
    "LABEL_BUDGET",
    "MAX_ADVANTAGES",
    "MAX_LIMITATIONS",
    "MAX_STORY_HOOKS",
    "SUMMARY_BUDGET",
    "TECHNICAL_LABELS",
    "candidate_player_copy",
    "candidate_player_copies",
    "copy_is_generic",
    "copy_is_redundant",
    "entity_type_for_field",
    "is_public_candidate",
    "player_copy_text",
    "player_safe_projection",
    "truncate_text",
]
