export const app = {
  context: null,
  view: "dashboard",
  overview: null,
  worlds: [],
  sessions: [],
  sessionOptions: [],
  sessionGroups: [],
  sessionQuery: "",
  sessionScope: "all",
  sessionPage: 1,
  sessionPageSize: 20,
  sessionTotal: 0,
  sessionPages: 1,
  providers: [],
  settings: null,
  configState: null,
  providerHealth: [],
  currentSession: null,
  memories: [],
  audit: [],
  deliveries: [],
  editorSave: null,
  sseId: null,
  refreshTimer: null,
  contextOff: null,
};

export const viewMeta = {
  dashboard: ["COMMAND CENTER", "运行总览"],
  worlds: ["WORLD LIBRARY", "世界与角色"],
  sessions: ["SESSION CONTROL", "群会话"],
  session_detail: ["LIVE OPERATIONS", "副本实时仪表盘"],
  todo: ["TODO QUEUE", "待办聚合"],
  memories: ["LONG-TERM MEMORY", "长期记忆"],
  audit: ["AUDIT TRAIL", "审计记录"],
  market: ["WORLD MARKET", "世界包市场"],
  settings: ["SECURITY BOUNDARY", "安全与设置"],
  about: ["ABOUT", "关于插件"],
};
